<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
      <UserSecretsId>08ffbe54-aa48-4836-b363-fa305b227c97</UserSecretsId>
      <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>

    <ItemGroup>
<PackageReference Include="FluentValidation" Version="12.1.1" />
        <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
        <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.7" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.4" />
        <PackageReference Include="Microsoft.AspNetCore.SignalR" Version="1.2.9" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.7">
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
          <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="OpenTelemetry.Exporter.Prometheus.AspNetCore" Version="1.17.0-beta.1" />
        <PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.17.0" />
        <PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.17.0" />
        <PackageReference Include="OpenTelemetry.Instrumentation.Http" Version="1.17.0" />
        <PackageReference Include="OpenTelemetry.Instrumentation.Runtime" Version="1.17.0" />
        <PackageReference Include="prometheus-net.AspNetCore" Version="8.2.1" />
        <PackageReference Include="Scalar.AspNetCore" Version="2.14.6" />
        <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
        <PackageReference Include="Serilog.Enrichers.Environment" Version="3.0.1" />
        <PackageReference Include="Serilog.Sinks.Elasticsearch" Version="10.0.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\IoT.Application\IoT.Application.csproj" />
      <ProjectReference Include="..\IoT.Contracts\IoT.Contracts.csproj" />
      <ProjectReference Include="..\IoT.Infrastructure\IoT.Infrastructure.csproj" />
      <ProjectReference Include="..\IoT.Shared\IoT.Shared.csproj" />
    </ItemGroup>

</Project>
