apiVersion: apps/v1
kind: Deployment
metadata:
  name: iot-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iot-api
  template:
    metadata:
      labels:
        app: iot-api
    spec:
      containers:
        - name: iot-api
          image: iotregistryi.azurecr.io/iot-api:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: iot-api-config
            - secretRef:
                name: iot-api-secret
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"